const state = { admin: null, dashboard: null, section: 'dashboard' };
const $ = selector => document.querySelector(selector);
const content = $('#content');

async function api(url, options = {}) {
    const response = await fetch(luneflixApiUrl(url), { credentials: 'include', ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } });
    const data = await response.json().catch(() => ({}));
    if (!response.ok) throw new Error(data.error || 'Não foi possível concluir a operação.');
    return data;
}

function toast(message) { const element = $('#toast'); element.textContent = message; element.classList.add('show'); setTimeout(() => element.classList.remove('show'), 2800); }
function money(value) { return Number(value || 0).toLocaleString('pt-BR', { style: 'currency', currency: 'BRL' }); }
function date(value) { return value ? new Date(value).toLocaleDateString('pt-BR') : 'Nunca'; }
function badge(value) { const type = value === 'active' || value === 'approved' ? 'success' : value === 'pending' ? 'warning' : value === 'blocked' || value === 'cancelled' ? 'danger' : 'neutral'; return `<span class="status-badge ${type}">${value}</span>`; }
function loading() { content.innerHTML = '<div class="panel empty">Carregando dados seguros...</div>'; }

function renderDashboard(data) {
    const m = data.metrics;
    content.innerHTML = `<div class="metric-grid">
        ${metric('Usuários totais', m.users, 'Base cadastrada')} ${metric('Usuários ativos', m.active_users, 'Contas disponíveis')} ${metric('Novos usuários', m.new_users, 'Últimos 30 dias')} ${metric('Assinaturas ativas', m.payments, 'Pagamentos aprovados')}
        ${metric('Receita total', money(m.revenue), 'Pagamentos aprovados')} ${metric('Pagamentos pendentes', m.pending, 'Aguardando análise')} ${metric('Filmes cadastrados', m.movies, 'Conteúdo publicado')} ${metric('Cupons ativos', m.coupons, 'Descontos disponíveis')}
    </div><div class="dashboard-grid"><section class="panel"><div class="panel-heading"><h2>Crescimento de usuários</h2><span>Dados disponíveis</span></div><div class="chart">${chartBars([m.new_users, m.active_users, m.users], ['Novos','Ativos','Total'])}</div></section><section class="panel"><div class="panel-heading"><h2>Status financeiro</h2><span>Agora</span></div><div class="ring-list"><div class="ring-row"><span>Pagamentos aprovados</span>${badge('approved')}<strong>${m.payments}</strong></div><div class="ring-row"><span>Pagamentos pendentes</span>${badge('pending')}<strong>${m.pending}</strong></div><div class="ring-row"><span>Receita confirmada</span><strong>${money(m.revenue)}</strong></div></div></section><section class="panel wide"><div class="panel-heading"><h2>Usuários recentes</h2><button class="text-button" data-go="users">Ver todos →</button></div>${userTable(data.recent_users)}</section><section class="panel"><div class="panel-heading"><h2>Atividade recente</h2></div>${data.logs.length ? data.logs.map(log => `<div class="ring-row"><span>${log.description}</span><small>${date(log.created_at)}</small></div>`).join('') : empty('Nenhuma ação registrada ainda.')}</section><section class="panel"><div class="panel-heading"><h2>Últimos pagamentos</h2></div>${data.recent_payments.length ? data.recent_payments.map(payment => `<div class="ring-row"><span>${payment.user_name || 'Usuário'}<small>${planName(payment.plan)}</small></span><strong>${money(payment.amount)}</strong></div>`).join('') : empty('Nenhum pagamento registrado.')}</section></div>`;
}
function metric(label, value, meta) { return `<article class="metric-card"><div class="metric-label">${label}</div><div class="metric-value">${value}</div><div class="metric-meta">${meta}</div></article>`; }
function chartBars(values, labels) { const max = Math.max(...values, 1); return values.map((value, index) => `<div class="bar" style="--height:${Math.max(value / max * 100, 6)}%;height:${Math.max(value / max * 100, 6)}%"><small>${labels[index]}</small></div>`).join(''); }
function empty(text) { return `<div class="empty"><strong>Sem dados para exibir</strong>${text}</div>`; }
function planName(plan) { return ({ basic: 'Básico', standard: 'Padrão', family: 'Padrão', premium: 'Premium', free: 'Gratuito' })[plan] || plan || 'Gratuito'; }
function userTable(users, actions = false) { if (!users.length) return empty('Cadastros aparecerão aqui.'); return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Usuário</th><th>Cargo</th><th>Plano</th><th>Status</th><th>Cadastro</th>${actions ? '<th>Ações</th>' : '<th>Último acesso</th>'}</tr></thead><tbody>${users.map(user => `<tr><td><div class="user-cell"><div class="mini-avatar">${user.name[0].toUpperCase()}</div><div><strong>${user.name}</strong><small>${user.email} · #${user.id}</small></div></div></td><td>${user.role}</td><td>${planName(user.plan)}</td><td>${badge(user.status)}</td><td>${date(user.created_at)}</td>${actions ? `<td><button class="table-action" data-user-action="edit" data-user-id="${user.id}" data-user-name="${user.name}" data-user-role="${user.role}" data-user-plan="${user.plan === 'family' ? 'standard' : (user.plan || 'free')}" data-user-status="${user.status}">Editar</button><button class="table-action" data-user-action="password" data-user-id="${user.id}" data-user-name="${user.name}">Senha</button><button class="table-action danger-action" data-user-action="delete" data-user-id="${user.id}" data-user-name="${user.name}">Excluir</button></td>` : `<td>${date(user.last_login)}</td>`}</tr>`).join('')}</tbody></table></div>`; }

async function showDashboard() { loading(); const result = await api('/api/admin/dashboard'); state.dashboard = result.data; renderDashboard(result.data); }
async function showUsers() { loading(); const result = await api('/api/admin/users'); content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Usuários da plataforma</h2><span>${result.data.length} registros encontrados</span></div></div><div class="toolbar"><input id="userSearch" placeholder="Pesquisar por nome, e-mail ou ID"><select id="userStatus"><option value="">Todos os status</option><option value="active">Ativos</option><option value="blocked">Bloqueados</option><option value="inactive">Inativos</option></select></div><div id="userResults">${userTable(result.data, true)}</div></section>`; const refresh = async () => { const params = new URLSearchParams(); if ($('#userSearch').value) params.set('search', $('#userSearch').value); if ($('#userStatus').value) params.set('status', $('#userStatus').value); const filtered = await api(`/api/admin/users?${params}`); $('#userResults').innerHTML = userTable(filtered.data, true); bindUserActions(); }; const bindUserActions = () => document.querySelectorAll('[data-user-action]').forEach(button => button.addEventListener('click', () => { if (button.dataset.userAction === 'edit') editUser(button.dataset); else if (button.dataset.userAction === 'password') resetUserPassword(button.dataset); else deleteUser(button.dataset); })); $('#userSearch').addEventListener('input', refresh); $('#userStatus').addEventListener('change', refresh); bindUserActions(); }
function closeUserModal() { document.querySelector('.user-modal')?.remove(); }
function openUserModal(user, mode) { const password = mode === 'password'; document.body.insertAdjacentHTML('beforeend', `<div class="user-modal"><div class="user-modal-card"><button class="modal-close" data-modal-close>×</button><p class="eyebrow">${password ? 'SEGURANÇA' : 'PERFIL DO USUÁRIO'}</p><h2>${password ? 'Alterar senha' : `Editar ${user.userName}`}</h2>${password ? '<label>Nova senha<input id="modalPassword" type="password" minlength="6" placeholder="Mínimo de 6 caracteres"></label>' : `<label>Cargo<select id="modalRole"><option value="user">Usuário</option><option value="manager">Gerente</option><option value="admin">Administrador</option></select></label><label>Plano<select id="modalPlan"><option value="free">Gratuito</option><option value="basic">Básico</option><option value="standard">Padrão</option><option value="premium">Premium</option></select></label><label>Status<select id="modalStatus"><option value="active">Ativo</option><option value="blocked">Bloqueado</option><option value="inactive">Inativo</option></select></label>`}<div class="modal-actions"><button class="secondary-button" data-modal-close>Cancelar</button><button class="primary-button" id="modalSave">Salvar <span>→</span></button></div></div></div>`); if (!password) { $('#modalRole').value = user.userRole; $('#modalPlan').value = user.userPlan; $('#modalStatus').value = user.userStatus; } document.querySelectorAll('[data-modal-close]').forEach(button => button.addEventListener('click', closeUserModal)); $('#modalSave').addEventListener('click', async () => { try { if (password) { await api(`/api/admin/users/${user.userId}/reset-password`, { method: 'POST', body: JSON.stringify({ password: $('#modalPassword').value }) }); } else { await api(`/api/admin/users/${user.userId}`, { method: 'PATCH', body: JSON.stringify({ role: $('#modalRole').value, plan: $('#modalPlan').value, status: $('#modalStatus').value }) }); } closeUserModal(); toast(password ? 'Senha alterada e ação registrada.' : 'Usuário atualizado e ação registrada.'); showUsers(); } catch (error) { toast(error.message); } }); }
async function editUser(user) { openUserModal(user, 'edit'); }
async function resetUserPassword(user) { openUserModal(user, 'password'); }
async function deleteUser(user) { if (!confirm(`Excluir definitivamente ${user.userName} do banco de dados?`)) return; try { await api(`/api/admin/users/${user.userId}`, { method: 'DELETE' }); toast('Usuário excluído e ação registrada.'); showUsers(); } catch (error) { toast(error.message); } }
async function showModules() { loading(); const result = await api('/api/admin/modules'); content.innerHTML = `<div class="section-grid">${result.data.map(module => `<article class="panel module-card"><div class="module-top"><div><h3>${module.name}</h3><p>${module.description}</p></div><button class="toggle ${module.status === 'active' ? '' : 'off'}" data-module="${module.key}" data-status="${module.status}" aria-label="Alternar ${module.name}"></button></div><small>Atualizado em ${date(module.updated_at)} · ${badge(module.status)}</small></article>`).join('')}</div>`; content.querySelectorAll('[data-module]').forEach(button => button.addEventListener('click', async () => { if (!confirm('Deseja alterar este módulo?')) return; await api(`/api/admin/modules/${button.dataset.module}`, { method: 'PATCH', body: JSON.stringify({ status: button.dataset.status }) }); toast('Módulo atualizado e ação registrada.'); showModules(); })); }
async function showSettings() { loading(); const result = await api('/api/admin/settings'); const settings = result.data; content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Configurações gerais</h2><span>Alterações são persistidas no banco e auditadas.</span></div></div><form id="settingsForm" class="settings-form"><label>Nome do aplicativo<input name="app_name" value="${settings.app_name || ''}" required></label><label>URL de suporte<input name="support_url" type="url" value="${settings.support_url || ''}" placeholder="https://..."/></label><label>Servidor Discord<input name="discord_url" type="url" value="${settings.discord_url || ''}" placeholder="https://discord.gg/..."/></label><div class="settings-actions"><button class="primary-button" type="submit">Salvar configurações <span>→</span></button></div></form></section>`; $('#settingsForm').addEventListener('submit', async event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.target)); await api('/api/admin/settings', { method: 'PUT', body: JSON.stringify(values) }); toast('Configurações salvas com sucesso.'); }); }
async function showLogs() { loading(); const result = await api('/api/admin/logs'); content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Logs do sistema</h2><span>Auditoria das ações administrativas</span></div></div>${result.data.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Data</th><th>Ação</th><th>Responsável</th><th>Descrição</th><th>Status</th></tr></thead><tbody>${result.data.map(log => `<tr><td>${date(log.created_at)}</td><td>${log.action}</td><td>${log.admin_name || 'Sistema'}</td><td>${log.description}</td><td>${badge(log.status)}</td></tr>`).join('')}</tbody></table></div>` : empty('As ações serão registradas aqui.')}</section>`; }
function financeTable(payments) {
    if (!payments.length) return empty('Nenhuma transação corresponde aos filtros aplicados.');
    return `<div class="table-wrap"><table class="data-table finance-table"><thead><tr><th>Transação</th><th>Cliente</th><th>Plano</th><th>Valor</th><th>Data</th><th>Status</th></tr></thead><tbody>${payments.map(payment => `<tr><td><strong>${payment.transaction_id}</strong><small>#${payment.id}</small></td><td><div class="finance-customer"><strong>${payment.user_name}</strong><small>${payment.user_email || `Usuário #${payment.user_id}`}</small></div></td><td><span class="plan-pill">${planName(payment.plan)}</span></td><td><strong>${money(payment.amount)}</strong></td><td>${date(payment.created_at)}</td><td>${badge(payment.status)}</td></tr>`).join('')}</tbody></table></div>`;
}

async function showFinance(filters = {}) {
    loading();
    const params = new URLSearchParams(Object.entries(filters).filter(([, value]) => value));
    const result = await api(`/api/admin/finance?${params}`);
    const data = result.data;
    const m = data.metrics;
    const chartValues = data.series.map(item => item.amount);
    const chartLabels = data.series.map(item => item.month ? item.month.split('-').reverse().join('/') : '—');
    content.innerHTML = `<section class="finance-intro panel"><div><p class="eyebrow">GESTÃO FINANCEIRA</p><h2>Receitas e transações</h2><p>Central preparada para a integração do gateway. Nenhuma cobrança é criada por esta tela.</p></div><div class="integration-state"><span class="status-dot"></span><div><strong>Gateway pendente</strong><small>Conexão será configurada na próxima etapa</small></div></div></section>
    <div class="metric-grid finance-metrics">${metric('Receita confirmada', money(m.revenue), `${m.approved_count} pagamentos aprovados`)}${metric('Em processamento', money(m.pending_value), `${m.pending_count} pagamentos pendentes`)}${metric('Transações canceladas', m.cancelled_count, 'Canceladas, falhas ou reembolsos')}${metric('Transações totais', m.total_count, 'Histórico financeiro')}</div>
    <div class="finance-layout"><section class="panel finance-chart"><div class="panel-heading"><div><h2>Recebimentos por mês</h2><span>Pagamentos aprovados</span></div></div>${data.series.length ? `<div class="chart">${chartBars(chartValues, chartLabels)}</div>` : empty('Os recebimentos aparecerão aqui após a integração.')}</section><section class="panel finance-next"><p class="eyebrow">PRÓXIMA ETAPA</p><h3>Gateway de pagamento</h3><p>Esta área receberá status, identificador do provedor, método de pagamento e eventos de webhook.</p><ul><li>Credenciais seguras no backend</li><li>Atualização automática de assinaturas</li><li>Conciliação de pagamentos</li></ul></section></div>
    <section class="panel finance-history"><div class="panel-heading"><div><h2>Histórico de transações</h2><span>${data.payments.length} registro(s) encontrado(s)</span></div></div><form id="financeFilters" class="toolbar finance-toolbar"><input name="search" value="${filters.search || ''}" placeholder="Transação, nome ou e-mail"><select name="status"><option value="">Todos os status</option><option value="approved" ${filters.status === 'approved' ? 'selected' : ''}>Aprovados</option><option value="pending" ${filters.status === 'pending' ? 'selected' : ''}>Pendentes</option><option value="cancelled" ${filters.status === 'cancelled' ? 'selected' : ''}>Cancelados</option><option value="failed" ${filters.status === 'failed' ? 'selected' : ''}>Falhos</option><option value="refunded" ${filters.status === 'refunded' ? 'selected' : ''}>Reembolsados</option></select><select name="plan"><option value="">Todos os planos</option>${data.plans.map(plan => `<option value="${plan}" ${filters.plan === plan ? 'selected' : ''}>${plan}</option>`).join('')}</select><button class="secondary-button" type="submit">Filtrar</button></form>${financeTable(data.payments)}</section>`;
    $('#financeFilters').addEventListener('submit', event => { event.preventDefault(); showFinance(Object.fromEntries(new FormData(event.currentTarget))); });
}
async function showMovies() { loading(); const result = await api('/api/admin/movies'); content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Catálogo de filmes</h2><span>${result.data.length} títulos cadastrados</span></div><button class="primary-button" id="newMovie">Adicionar filme <span>+</span></button></div>${result.data.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Título</th><th>Gênero</th><th>Ano</th><th>Destaque</th><th>Status</th></tr></thead><tbody>${result.data.map(movie => `<tr><td><strong>${movie.title}</strong></td><td>${movie.genre}</td><td>${movie.year || '-'}</td><td>${movie.featured ? 'Sim' : 'Não'}</td><td>${badge(movie.status)}</td></tr>`).join('')}</tbody></table></div>` : empty('Adicione o primeiro título ao catálogo.')}</section>`; $('#newMovie').addEventListener('click', () => { content.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Novo filme</h2></div><form id="movieForm" class="settings-form"><label>Título<input name="title" required></label><label>Gênero<input name="genre" value="Drama" required></label><label>Categoria<input name="category" value="Filme" required></label><label>Ano<input name="year" type="number"></label><label>Duração (minutos)<input name="duration" type="number"></label><label>Classificação<input name="rating"></label><label>URL do poster<input name="poster_url" type="url"></label><label>URL do banner<input name="banner_url" type="url"></label><label>URL do vídeo<input name="video_url" type="url"></label><label>Descrição<textarea name="description" rows="3"></textarea></label><div class="settings-actions"><button class="primary-button">Salvar filme <span>→</span></button></div></form></section>`; $('#movieForm').addEventListener('submit', async event => { event.preventDefault(); await api('/api/admin/movies', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); toast('Filme criado e ação registrada.'); showMovies(); }); }); }
async function showCoupons() { loading(); const result = await api('/api/admin/coupons'); content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Cupons promocionais</h2><span>${result.data.length} cupons cadastrados</span></div><button class="primary-button" id="newCoupon">Criar cupom <span>+</span></button></div>${result.data.length ? `<div class="table-wrap"><table class="data-table"><thead><tr><th>Código</th><th>Desconto</th><th>Usos</th><th>Validade</th><th>Status</th></tr></thead><tbody>${result.data.map(coupon => `<tr><td><strong>${coupon.code}</strong></td><td>${coupon.discount_value}${coupon.discount_type === 'percent' ? '%' : ' BRL'}</td><td>${coupon.usage_count}/${coupon.usage_limit || '∞'}</td><td>${date(coupon.expires_at)}</td><td>${badge(coupon.status)}</td></tr>`).join('')}</tbody></table></div>` : empty('Crie um cupom para iniciar as promoções.')}</section>`; $('#newCoupon').addEventListener('click', () => { content.innerHTML = `<section class="panel"><div class="panel-heading"><h2>Novo cupom</h2></div><form id="couponForm" class="settings-form"><label>Código<input name="code" required placeholder="LUNE20"></label><label>Tipo<select name="discount_type"><option value="percent">Porcentagem</option><option value="fixed">Valor fixo</option></select></label><label>Desconto<input name="discount_value" type="number" min="0" step="0.01" required></label><label>Expira em<input name="expires_at" type="date"></label><label>Limite de usos<input name="usage_limit" type="number" min="1"></label><div class="settings-actions"><button class="primary-button">Salvar cupom <span>→</span></button></div></form></section>`; $('#couponForm').addEventListener('submit', async event => { event.preventDefault(); await api('/api/admin/coupons', { method: 'POST', body: JSON.stringify(Object.fromEntries(new FormData(event.target))) }); toast('Cupom criado e ação registrada.'); showCoupons(); }); }); }
function showPlaceholder(name, detail) { content.innerHTML = `<section class="panel empty"><strong>${name}</strong>${detail}</section>`; }
async function showCatalog() {
    loading();
    const result = await api('/api/admin/catalog');
    const rows = result.data;
    content.innerHTML = `<section class="panel"><div class="panel-heading"><div><h2>Gerenciar catálogo</h2><span>${rows.length} títulos na base local</span></div></div><form id="catalogForm" class="settings-form"><label>IMDb ID do filme<input name="imdb_id" required pattern="tt[0-9]+" placeholder="tt22084616"></label><div class="settings-actions"><button class="primary-button">Buscar prévia <span>→</span></button></div></form><div id="catalogPreview"></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Título</th><th>Tipo</th><th>IMDb/TMDB</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>${rows.map(item => `<tr><td><strong>${item.title}</strong></td><td>${item.type === 'movie' ? 'Filme' : 'Série'}</td><td>${item.imdb_id || item.tmdb_id || '-'}</td><td>${date(item.updated_at)}</td><td><button class="table-action danger-action" data-catalog-delete="${item.type}" data-catalog-id="${item.id}">Remover</button></td></tr>`).join('')}</tbody></table></div></section>`;
    $('#catalogForm').addEventListener('submit', async event => {
        event.preventDefault();
        const imdbId = new FormData(event.target).get('imdb_id');
        const found = await api(`/api/search?q=${encodeURIComponent(imdbId)}`);
        const movie = found.results.find(item => item.media_type === 'movie' && item.imdb_id === imdbId);
        if (!movie) return toast('Filme não encontrado. Confira o IMDb ID.');
        $('#catalogPreview').innerHTML = `<div class="panel"><h3>${movie.title}</h3><p>${movie.overview || 'Sem sinopse disponível.'}</p><button class="primary-button" id="confirmCatalog">Confirmar cadastro</button></div>`;
        $('#confirmCatalog').addEventListener('click', async () => { await api('/api/admin/catalog', { method: 'POST', body: JSON.stringify(movie) }); toast('Filme cadastrado no catálogo local.'); showCatalog(); });
    });
    content.querySelectorAll('[data-catalog-delete]').forEach(button => button.addEventListener('click', async () => { if (!confirm('Remover este item do catálogo?')) return; await api(`/api/admin/catalog/${button.dataset.catalogDelete}/${button.dataset.catalogId}`, { method: 'DELETE' }); toast('Item removido.'); showCatalog(); }));
}

async function navigate(section) { state.section = section; document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.section === section)); const names = { dashboard: ['VISÃO GERAL','Dashboard'], users: ['CONTAS','Usuários'], finance: ['FINANCEIRO','Gestão financeira'], movies: ['CATÁLOGO','Filmes'], modules: ['PLATAFORMA','Módulos'], coupons: ['PROMOÇÕES','Cupons'], settings: ['SISTEMA','Configurações'], logs: ['AUDITORIA','Logs'] }; $('#sectionKicker').textContent = names[section][0]; $('#sectionTitle').textContent = names[section][1]; try { if (section === 'dashboard') await showDashboard(); else if (section === 'users') await showUsers(); else if (section === 'finance') await showFinance(); else if (section === 'movies') await showCatalog(); else if (section === 'modules') await showModules(); else if (section === 'coupons') await showCoupons(); else if (section === 'settings') await showSettings(); else if (section === 'logs') await showLogs(); else showPlaceholder(names[section][1], 'Nenhum registro persistente disponível ainda.'); } catch (error) { content.innerHTML = `<section class="panel empty"><strong>Não foi possível carregar</strong>${error.message}</section>`; } }

document.querySelectorAll('.nav-item').forEach(item => item.addEventListener('click', () => navigate(item.dataset.section)));
document.addEventListener('click', event => { const target = event.target.closest('[data-go]'); if (target) navigate(target.dataset.go); });
$('#adminLoginForm').addEventListener('submit', async event => { event.preventDefault(); $('#loginError').textContent = ''; const button = event.target.querySelector('button'); button.disabled = true; try { const result = await api('/api/admin/login', { method: 'POST', body: JSON.stringify({ email: $('#adminEmail').value, password: $('#adminPassword').value }) }); state.admin = result.admin; $('#adminName').textContent = result.admin.name; $('#adminAvatar').textContent = result.admin.name[0].toUpperCase(); $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); navigate('dashboard'); } catch (error) { $('#loginError').textContent = error.message; } finally { button.disabled = false; } });
$('#logoutButton').addEventListener('click', async () => { await api('/api/admin/logout', { method: 'POST' }); location.reload(); });
api('/api/admin/me').then(result => { state.admin = result.admin; $('#adminName').textContent = result.admin.name; $('#adminAvatar').textContent = result.admin.name[0].toUpperCase(); $('#loginView').classList.add('hidden'); $('#appView').classList.remove('hidden'); navigate('dashboard'); }).catch(() => {});
